### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by drewprice**
This pull request has been automatically created by learn.co

### CODE REVIEW

**Comment by aviflombaum** [comment]
@drewprice thanks for the change - I wonder why you think that `...then` adds more clarity than starting a new sentence?

**Comment by drewprice** [comment]
@aviflombaum My thinking was that, because the Bash line is an interruption, a new sentence makes the previous sentence a fragment: ```However, if you get: [learn is not installed] Then you need to install Learn.```

The ellipses probably isn't the best fix, but it's an attempt to pick up where the interruption leaves off: ```However, if you get: [learn is not installed] ...then you need to install Learn.```


So for fun, the logic with a new sentence looks like this:
```Ruby
if learn_is_not_installed
end

install_learn
```
...while the change aims to look like this:
```Ruby
if learn_is_not_installed
  install_learn
end
```

**Comment by roseweixel** [comment]
@drewprice, perhaps a better fix would be to change it to

However, if you get `-bash: learn: command not found`, then you need to install Learn. 

@SophieDeBenedetto

**Comment by drewprice** [comment]
@roseweixel briiiilliant!

**Pull request closed without merging**
